### ISSUE TITLE
Implement validator for site object in site_level_configuration file

### ISSUE THREAD

**Issue by maany** [WLCG-Lightweight-Sites/wlcg_lightweight_site_config_validation_engine#3]
Write schema and validators required to validate the following data:
```
site:
  name: simple-dev-site
  email: mayank.sharma@cern.ch
  latitude: 46.3
  longitude: 6.2
  location: CERN, Geneva, Switzerland
  description: A demo site demonstrating the SIMPLE framework for site setup
  website: https://home.cern
  support_website: https://groups.google.com/forum/#!forum/wlcg-lightweight-sites
  support_email: mayank.sharma@cern.ch
  security_email: mayank.sharma@cern.ch
  grid: wlcg
  tier: 3
  bdii_host: bdii.cern.ch
  use_argus: false
```
