### ISSUE TITLE
Implement validator for site_infrastructure object in site_level_configuration file

### ISSUE THREAD

**Issue by maany** [WLCG-Lightweight-Sites/wlcg_lightweight_site_config_validation_engine#4]
Write schema and validators needed to validate the following data:
```
site_infrastructure:
- fqdn: lightweight_component01.cern.ch
  ip_address: 192.168.0.4
- fqdn: lightweight_component02.cern.ch
  ip_address: 192.168.0.5
```
