### ISSUE TITLE
Implement validator for voms_config object in site_level_configuration file

### ISSUE THREAD

**Issue by maany** [WLCG-Lightweight-Sites/wlcg_lightweight_site_config_validation_engine#5]

**Comment by maany** [comment]
Write schema and validators needed to validate the following data:
```
voms_config:
- voms_fqan: /alice
  pool_accounts:
  - base_name: alice
    initial_uid: 10417
    users_num: 5
    primary_group:
      gid: 1395
      name: alice
    secondary_groups: []
  vo:
    name: alice
    servers:
    - server: voms2.cern.ch
      port: '15000'
      dn: /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
      ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
    - server: lcg-voms2.cern.ch
      port: '15000'
      dn: /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
      ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
    default_se: not_used.some-domain
    sw_dir: .
    storage_dir: /not/used
- voms_fqan: /alice/ROLE=lcgadmin
  pool_accounts:
  - base_name: alice
    initial_uid: 10417
    users_num: 5
    primary_group:
      gid: 1395
      name: alice
    secondary_groups: []
  - base_name: sgmali
    initial_uid: 60101
    users_num: 10
    primary_group:
      gid: 1397
      name: alicesgm
    secondary_groups:
    - gid: 1395
      name: alice
  vo:
    name: alice
    servers:
    - server: voms2.cern.ch
      port: '15000'
      dn: /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
      ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
    - server: lcg-voms2.cern.ch
      port: '15000'
      dn: /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
      ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
    default_se: not_used.some-domain
    sw_dir: .
    storage_dir: /not/used
  comment: sgm
- voms_fqan: /dteam
  pool_accounts:
  - base_name: dteam
    initial_uid: 18118
    users_num: 10
    primary_group:
      gid: 2688
      name: dteam
    secondary_groups: []
  vo:
    name: dteam
    servers:
    - server: voms2.cern.ch
      port: '15001'
      dn: /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
      ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
    - server: lcg-voms2.cern.ch
      port: '15001'
      dn: /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
      ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
    default_se: not_used.some-domain
    sw_dir: .
    storage_dir: /storage/dteam
- voms_fqan: /dteam/ROLE=lcgadmin
  pool_accounts:
  - base_name: sgmdtm
    initial_uid: 60501
    users_num: 5
    primary_group:
      gid: 2680
      name: dteamsgm
    secondary_groups:
    - gid: 2688
      name: dteam
  - base_name: dteam
    initial_uid: 18118
    users_num: 10
    primary_group:
      gid: 2688
      name: dteam
    secondary_groups: []
  vo:
    name: dteam
    servers:
    - server: voms2.cern.ch
      port: '15001'
      dn: /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
      ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
    - server: lcg-voms2.cern.ch
      port: '15001'
      dn: /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
      ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
    default_se: not_used.some-domain
    sw_dir: .
    storage_dir: /storage/dteam
  comment: sgm
- voms_fqan: /ops
  vo:
    name: ops
    servers:
    - server: voms2.cern.ch
      port: '15009'
      dn: /DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch
      ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
    - server: lcg-voms2.cern.ch
      port: '15009'
      dn: /DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch
      ca_dn: /DC=ch/DC=cern/CN=CERN Grid Certification Authority
    default_se: not_used.some-domain
    sw_dir: .
    storage_dir: /storage/ops
  pool_accounts:
  - base_name: ops
    initial_uid: 45001
    users_num: 10
    primary_group:
      gid: 45000
      name: ops
    secondary_groups: []
- voms_fqan: /ops/ROLE=lcgadmin
  pool_accounts:
  - base_name: sgmops
    initial_uid: 60701
    users_num: 10
    primary_group:
      gid: 45000
      name: ops
    secondary_groups:
    - gid: 46001
      name: opssgm
  - base_name: ops
    initial_uid: 45001
    users_num: 10
    primary_group:
      gid: 45000
      name: ops
    secondary_groups: []
```
